//
//  UIColor+YBKAdditions.swift
//
//  Generated by Zeplin on 4/19/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class func ybkBrownishColor() -> UIColor {
		return UIColor(red: 160.0 / 255.0, green: 98.0 / 255.0, blue: 90.0 / 255.0, alpha: 1.0)
	}

	class func ybkSandBrownColor() -> UIColor {
		return UIColor(red: 211.0 / 255.0, green: 150.0 / 255.0, blue: 104.0 / 255.0, alpha: 1.0)
	}

	class func ybkDarkSalmonColor() -> UIColor {
		return UIColor(red: 204.0 / 255.0, green: 113.0 / 255.0, blue: 93.0 / 255.0, alpha: 1.0)
	}

	class func ybkPaleColor() -> UIColor {
		return UIColor(red: 255.0 / 255.0, green: 239.0 / 255.0, blue: 214.0 / 255.0, alpha: 1.0)
	}
}
