//
//  UIFont+YBKAdditions.swift
//
//  Generated by Zeplin on 4/19/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func ybkTextStyleFont() -> UIFont? {
		return UIFont(name: "Helvetica-Bold", size: 80.0)
	}

	class func ybkTextStyle2Font() -> UIFont? {
		return UIFont(name: "PingFangTC-Medium", size: 20.0)
	}
}
